version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.20
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn install
      - run: CI=true yarn run build
  test:
    docker:
      - image: circleci/node:12.20
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: yarn install
      - run: yarn test
  hithere:
    docker:
      - image: circleci/node:12.20
    steps:
      - checkout
      - run: echo "helllooooo!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere